# create dynatrace alerting profile with management zone
# host_name -> target host to execute playbook
# dt_config_api_endpoint -> dynatrace configuration api endpoint (include trailing /)
# dt_api_token -> dynatrace api token with read & write access
# dt_mz_name -> name of existing dynatrace management zone (used to name alerting profile)
# dt_mz_64id -> unique 64 bit integer id of existing management zone
# dt_ap_uuid -> unique UUID to assign new alerting profile
---
-
  hosts: "{{ host_name }}"
  name: "create dynatrace alerting profile with management zone"
  tasks:
    -
      name: validate alerting profile uuid is available
      uri:
        url: "{{ dt_config_api_endpoint }}alertingProfiles?Api-Token={{ dt_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: existing_ap
      failed_when: 'dt_ap_uuid|string in existing_ap.content'
    -
      name: validate management zone 64 bit id exists
      uri:
        url: "{{ dt_config_api_endpoint }}managementZones?Api-Token={{ dt_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: existing_mz
      #failed_when: "'{{ dt_mz_64id }}' not in existing_mz.content"
      failed_when: 'dt_mz_64id|string not in existing_mz.content'
    -
      name: validate alerting profile payload
      uri:
        url: "{{ dt_config_api_endpoint }}alertingProfiles/validator?Api-Token={{ dt_api_token }}"
        method: POST
        body:
          displayName: "{{ dt_mz_name }}"
          rules:
          - severityLevel: ERROR
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: PERFORMANCE
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: RESOURCE_CONTENTION
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: CUSTOM_ALERT
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          - severityLevel: MONITORING_UNAVAILABLE
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          - severityLevel: AVAILABILITY
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          managementZoneId: "{{ dt_mz_64id }}"
          eventTypeFilters: []
        body_format: json
        status_code: 204
        return_content: yes
      register: new_mz
    -
      name: create alerting profile
      uri:
        url: "{{ dt_config_api_endpoint }}alertingProfiles/{{ dt_ap_uuid }}?Api-Token={{ dt_api_token }}"
        method: PUT
        body:
          id: "{{ dt_ap_uuid }}"
          displayName: "{{ dt_mz_name }}"
          rules:
          - severityLevel: ERROR
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: PERFORMANCE
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: RESOURCE_CONTENTION
            tagFilter:
              includeMode: NONE
            delayInMinutes: 15
          - severityLevel: CUSTOM_ALERT
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          - severityLevel: MONITORING_UNAVAILABLE
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          - severityLevel: AVAILABILITY
            tagFilter:
              includeMode: NONE
            delayInMinutes: 0
          managementZoneId: "{{ dt_mz_64id }}"
          eventTypeFilters: []
        body_format: json
        status_code: 201
        return_content: yes
      register: new_mz
