# create dynatrace alerting profile with management zone
# host_name
# dt_config_api_endpoint
# dt_api_token
# dt_mz_name
# dt_mz_uuid
# dt_ap_uuid
---
-
  hosts: "{{ host_name }}"
  name: "create dynatrace alerting profile with management zone"
  tasks:
    -
      name: validate alerting profile uuid is available
      uri:
        url: "{{ dt_config_api_endpoint }}alertingProfiles?Api-Token={{ dt_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: existing_ap
      failed_when: "'{{ dt_ap_uuid }}' in existing_ap.content"
    -
      name: validate management zone uuid exists
      uri:
        url: "{{ dt_config_api_endpoint }}managementZones?Api-Token={{ dt_api_token }}"
        method: GET
        return_content: yes
        status_code: 200
      register: existing_mz
      failed_when: "'{{ dt_mz_uuid }}' not in existing_mz.content"
    -
      name: validate alerting profile payload
      uri:
        url: "{{ dt_config_api_endpoint }}alertingProfiles/validator?Api-Token={{ dt_api_token }}"
        method: POST
        body:
          displayName: "{{ dt_mz_name }}"
          rules:
          - severityLevel: ERROR
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: PERFORMANCE
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: RESOURCE_CONTENTION
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: CUSTOM_ALERT
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          - severityLevel: MONITORING_UNAVAILABLE
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          - severityLevel: AVAILABILITY
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          managementZoneId: "{{ dt_mz_uuid }}"
          eventTypeFilters: []
        body_format: json
        status_code: 204
        return_content: yes
      register: new_mz
    -
      name: create alerting profile
      uri:
        url: "{{ dt_config_api_endpoint }}managementZones/{{ dt_mz_uuid }}?Api-Token={{ dt_api_token }}"
        method: PUT
        body:
          id: "{{ dt_ap_uuid }}"
          displayName: "{{ dt_mz_name }}"
          rules:
          - severityLevel: ERROR
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: PERFORMANCE
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: RESOURCE_CONTENTION
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 15
          - severityLevel: CUSTOM_ALERT
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          - severityLevel: MONITORING_UNAVAILABLE
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          - severityLevel: AVAILABILITY
            tagFilter:
              includeMode: NONE
              tagFilters: []
            delayInMinutes: 0
          managementZoneId: "{{ dt_mz_uuid }}"
          eventTypeFilters: []
        body_format: json
        status_code: 201
        return_content: yes
      register: new_mz
