# dynatrace oneagent install on windows
# hosts_group -> inventory group of hosts to execute playbook on
# dt_api_endpoint -> dynatrace environment api endpoint (include trailing /)
# dt_api_token -> dynatrace api install token
# dt_host_group: -> dynatrace host group name
# dt_app_log_content_access: -> flag to enable or disable log analytics on host (0 or 1)
# dt_infra_only: -> flag to set cloud infrastructure monitoring mode on host (0 or 1)
## deprecated product id 158D01AC-3A0A-49A3-BF3A-566F6365EDE7 with version 1.183.136
---
-
  hosts: "{{ hosts_group }}"
  name: "dynatrace oneagent install on windows"
  tasks:
    -
      name: "validate ansible tower execution on windows"
      win_stat:
        path: C:\Temp
      register: temp_dir
    -
      name: "check if oneagent is already installed via windows registry product id"
      win_reg_stat:
        path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{9257BAF1-3E45-42F9-BBB5-48D5DDD98105}
        name: DisplayName
      register: installed
    -
      name: "download oneagent install file"
      win_get_url:
        url: "{{ dt_api_endpoint }}deployment/installer/agent/windows/default/latest?Api-Token={{ dt_api_token }}&arch=x86&flavor=default"
        dest: C:\Temp\dynatrace-oneagent-windows-latest.exe
    -
      name: "extract oneagent install msi file"
      win_command: C:\Temp\dynatrace-oneagent-windows-latest.exe --unpack-msi C:\Temp
      args:
        chdir: C:\Temp
    -
      name: "identify oneagent install msi file"
      win_command: dir /b Dynatrace-OneAgent-Windows-*msi
      args:
        chdir: C:\Temp
      register: oneagent_msi
    -
      name: "output oneagent_msi"
      debug:
        msg: "{{ oneagent_msi }}"
    #-
      #name: "install: execute oneagent install file"
      #win_package:
        #path: "C:\\Temp\\{{ oneagent_msi }}"
        ##product_id: '{9257BAF1-3E45-42F9-BBB5-48D5DDD98105}'
        #arguments:
        #- HOST_GROUP="{{ dt_host_group }}"
        #- APP_LOG_CONTENT_ACCESS="{{ dt_app_log_content_access }}"
        #- INFRA_ONLY="{{ dt_infra_only }}"
        #state: present
      #when: installed.exists == False
    #-
      #name: "update: uninstall existing oneagent package"
      #win_package:
        #product_id: '{9257BAF1-3E45-42F9-BBB5-48D5DDD98105}'
        #state: absent
      #when: installed.exists == True
    #-
      #name: "update: execute oneagent install file"
      #win_package:
        #path: C:\Temp\dynatrace-oneagent-windows-latest.exe
        #product_id: '{9257BAF1-3E45-42F9-BBB5-48D5DDD98105}'
        #arguments:
        #- HOST_GROUP="{{ dt_host_group }}"
        #- APP_LOG_CONTENT_ACCESS="{{ dt_app_log_content_access }}"
        #- INFRA_ONLY="{{ dt_infra_only }}"
        #state: present
      #when: installed.exists == True
