# dynatrace oneagent install on windows
---
-
  hosts: all
  name: "dynatrace oneagent install on windows"
  tasks:
    -
      name: check if oneagent is already installed
      win_reg_stat:
        path: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dynatrace OneAgent
        name: ImagePath
      register: dt_reg_key
#    not ready
#    -
#      name: check if oneagent binary exists
#      win_stat:
#        path: {{ dt_reg_key.value }}
#      register: dt_binary_file
    -
      name: download oneagent install file via https
      get_url:
        url: https://hfn13693.live.dynatrace.com/api/v1/deployment/installer/agent/windows/default/latest?Api-Token={{ dt_install_token }}&arch=x86&flavor=default
        dest: C:\Temp\dynatrace-oneagent-windows-latest.exe
    -
      name: "execute oneagent install file"
      win_package:
        path: C:\Temp\dynatrace-oneagent-windows-latest.exe
        arguments: /S
        state: present
