# initiate easytravel security change
---
-
  hosts: localhost
  name: "initiate easytravel security change"
  tasks:
    -
      name: call easytravel configuration UI
      uri:
        url: "http://{{ easytravel_host }}:8091/services/ConfigurationService/setPluginEnabled?name={{ easytravel_plugin }}&enabled={{ easytravel_plugin_state }}"
        status_code: 202
    -
      name: download custom configuration event file
      get_url:
        url: https://tpc-easytravel-demo.s3.amazonaws.com/security_configuration.json
        dest: /tmp/
        mode: '0666'
    -
      name: create custom configuration event
      uri:
        url: https://{{ dynatrace_api_url }}/api/v1/events?Api-Token={{ dynatrace_token }}
        method: POST
        headers:
          content-type: application/json
        src: /tmp/security_configuration.json
        remote_src: yes
        status_code: 200
