# deprecated - added functionality to 'dt-oneagent-install-windows.yml'
# validate ansible tower execution on windows
# hosts_group -> inventory group of hosts to execute playbook on
---
-
  hosts: "{{ hosts_group }}"
  name: "validate ansible tower execution on windows"
  tasks:
    -
      name: "check if the c:\temp directory exists"
      win_stat:
        path: C:\Temp
      register: temp_dir
